name: CI/CD

on:
  push:
    branches: ["master", "develop"]
  pull_request:
    branches: ["master", "develop"]
  workflow_dispatch:

jobs:
  ci:
    name: Run ESLint + Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Set up npm and Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint:check

      - name: Run Prettier
        run: npm run format:check

  cd:
    name: Deploy to GCP VM
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            cd key-provision-bot

            # Pull latest changes from master branch (echo to see)
            git checkout master
            git rev-parse --abbrev-ref HEAD

            # Install dependencies and deploy the commands
            npm ci
            npm run deploy-commands

            # Restart the bot
            sudo systemctl restart key-provision-bot
